language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
# Support library
    - extra-android-support
    - extra-google-google_play_services

before_script:
    - chmod +x gradlew

script:
   - chmod +x ./gradlew
   - ./gradlew assembleDebug assembleRelease
